### ISSUE TITLE
not found resources

### ISSUE THREAD

**Issue by youngherna** [TheXPerienceProject/android_packages_apps_Launcher3#1]
packages/apps/Launcher3/res/xml/grayscale_icon_map.xml:296: error: resource drawable/themed_icon_tinkoff (aka com.android.launcher3:drawable/themed_icon_tinko not found.
packages/apps/Launcher3/res/xml/grayscale_icon_map.xml:297: error: resource drawable/themed_icon_tinkoff (aka com.android.launcher3:drawable/themed_icon_tinko not found.
packages/apps/Launcher3/res/xml/grayscale_icon_map.xml:298: error: resource drawable/themed_icon_tinkoff (aka com.android.launcher3:drawable/themed_icon_tinko not found.
error: failed linking file resources.

**Comment by Klozz** [comment]
Fixed in https://github.com/TheXPerienceProject/android_packages_apps_Launcher3/commit/e561b4dc7d743d3f8968f7e41c4a9dfaed6f6c23
